== 些许简单数学

[.text-center]
<<_序言,icon:level-up[]>>
-
<<_简单时钟系统,icon:level-down[]>>

'''

=== 命题逻辑

初等代数是关于实数和四则运算（加减乘除四个运算符）的数学。命题逻辑是两个布尔值，真（TRUE）和假（FALSE）再加上以下五个运算符的数学：

latexmath:[\wedge]:: 逻辑与
latexmath:[\vee]:: 逻辑或
latexmath:[\neg]:: 逻辑取反
latexmath:[\implies]:: 实质蕴涵或暗含。*译者注*：一般来说命题逻辑里的实质蕴涵一般使用单线箭头 latexmath:[\rightarrow]，不清楚Lamport老爷爷为啥使用双线箭头。可能是避免和在函数定义里使用的单线箭头冲突吧。
latexmath:[\equiv]:: 逻辑等价

在学习初等代数的时候，我们得记住加法乘法表，以及多位数的运算法则。命题逻辑就简单的多了，原因是命题逻辑只有两个值，真和假。掌握逻辑运算，只需要了解以下五个布尔运算符的定义：

latexmath:[\wedge]:: latexmath:[F \wedge G] 为真，当且仅当 latexmath:[F] 和 latexmath:[G] 都为真。
latexmath:[\vee]:: latexmath:[F \vee G] 为真，当且仅当 latexmath:[F] 或者 latexmath:[G] 为真（当然也包含两者都为真的情况，因为我们一般用“或”来表示”或“或者”与“）。
latexmath:[\neg]:: latexmath:[\neg F] 为真，当且仅当 latexmath:[F] 为假。
latexmath:[\implies]:: latexmath:[F \implies G] 为真，当且仅当 latexmath:[F] 为假，或者 latexmath:[G] 为真。
latexmath:[\equiv]:: latexmath:[F \equiv G] 为真，当且仅当 latexmath:[F] 和 latexmath:[G] 同为真，或同为假。

我们也可以用真值表（truth table）来描述这些运算符的含义。下面这个真值表给出了 latexmath:[F] 和 latexmath:[G] 取值所有组合所对应的 latexmath:[F \implies G] 的值。

[options=noheader, width=50%]
|===

| latexmath:[F] | latexmath:[G] | latexmath:[F \implies G]

| 真 | 真 | 真

| 真 | 假 | 假

| 假 | 真 | 真

| 假 | 假 | 真
|===


很多人觉得实质蕴涵的定义有点绕，不太明白为什么 latexmath:[FALSE \implies TRUE] 和 latexmath:[FALSE \implies FALSE] 为真。要理解为什么其实也很简单。大家应该都能同意说如果一个数 latexmath:[n > 3]，那么它应该大于1。因此，公式 latexmath:[(n>3) \implies (n>1) ] 应该为真。把公式中的 latexmath:[n] 分别替换成4，2和0后再去审视该公式的含义，应能帮助大家理解为什么 latexmath:[F \implies G] 意思是 latexmath:[F] __暗含__ latexmath:[G]，或者说是，__如果__ latexmath:[F] __则__ latexmath:[G]。

等价操作符 latexmath:[\equiv] 就是布尔类型表达式的相等关系（equality）。我们可以把 latexmath:[\equiv] 替换成 latexmath:[=]，但反过来不行（可以写 latexmath:[FALSE = \neg TRUE]，但不可以写 latexmath:[2+2 \equiv 4]）。为了清楚的表明相等关系的表达式是布尔类型，推荐使用 latexmath:[\equiv] 而不是 latexmath:[=]（第16.1.3节会更详细的解释为什么应该用latexmath:[\equiv]）。

命题逻辑的公式由值，操作符，以及代表某个值的标识符（比如 latexmath:[x]）组成，而且比一般的代数简单，命题逻辑只有2两个值，和5个操作符。代数公式里的乘号*比加号+的优先级高，例如 latexmath:[x+y*z] 意思是 latexmath:[x+(y*z)]。同样的取反符号的优先级要高于与和或，而与和或又高于暗含和等价。其他的一些数学操作符，比如+和>又比命题逻辑的操作符高。如果对优先级有任何的一点点不确定，请多使用括号，这样公式的可读性也会提高。

与和或满足结合律（associative)，和加号和乘号一样。因为满足了结合律，我们可以写成 latexmath:[x+y+z] 和 latexmath:[F \wedge G \wedge H] 而无需括号。与和或也满足交换律（commutative），因此 latexmath:[F \wedge G] 与 latexmath:[G \wedge F] 等价。

公式 latexmath:[(x=2) \implies (x+1=3)] 在陈述一个关于数字的事实。去判断该公式是否为真，我们必须得懂得一些基本的算术知识。另一个公式 latexmath:[(x=2) \implies (x=2）\vee (y>7)] 就不一样了。求得它的值并不需要我们去懂得任何算术的知识。这里原因是这个公式是 latexmath:[F \implies F \vee G] 一个特例，而不论 latexmath:[F] 和 latexmath:[G] 是什么，后者都为真。这样的公式我们称作**恒真式**（tautology）。

命题逻辑中简单的恒真式应该很容易判断的出来，就像代数里的简单恒等式一样，比如 latexmath:[F \implies F \vee G] 和 latexmath:[x \leq x + y]。同样的，我们可以从简单的恒真式，推导出复杂的恒真式。一般来所大家对初等代数的熟悉程度会远高于命题逻辑，因此大家可能很容易从 latexmath:[x \leq -x+y] 得到 latexmath:[2 * x  \implies y]，而对从 latexmath:[\neg F \vee G] 等价于 latexmath:[F \implies G] 感到陌生。

我们每个人从掰手指数数开始学习算术，从零开始学习布尔表达式的各种变换也需要类似的入门方法。手动构造一个公式的真值表就是最好的入门方法。在真值表里，一个公式中所有的变量取值组合，以及所有子公式的取值全部都列举出来。举个例子，由下面这个真值表我们就可以得出 latexmath:[(F \implies G) \equiv (\neg F \vee G)] 是恒等式。

[cols="1,1,2,2,2,4",options=noheader, width=90%]
|===

| latexmath:[F] | latexmath:[G] | latexmath:[F \implies G] | latexmath:[\neg F] | latexmath:[\neg F \vee G] | latexmath:[(F \implies G) \equiv \neg F \vee G]

| 真 | 真 | 真 | 假 | 真 | 真

| 真 | 假 | 假 | 假 | 假 | 真

| 假 | 真 | 真 | 真 | 真 | 真

| 假 | 假 | 真 | 真 | 真 | 真

|===


=== 集合

TODO.

=== 谓词逻辑

有了集合之后，就自然而然地想去声明某个公式对于一个集合中所有的元素都为真，或者只对一个集合中某些元素为真。谓词逻辑（predicate logic）相对于命题逻辑， 增加了两个量词（quantifiers）：

latexmath:[\forall]:: 全称量词
latexmath:[\exists]:: 存在量词

公式 latexmath:[\forall x \in S : F] 表示公式 latexmath:[F] 对于集合S中**每一个**元素来说都为真。例如，latexmath:[\forall n \in Nat : n + 1 > n] 表示公式 latexmath:[n + 1 > n] 对于每一个自然数来说都为真。该公式确实为真。

公式 latexmath:[\exists x \in S : F] 表示公式 latexmath:[F] 对于集合S中**至少一个**元素x来说都为真。例如，latexmath:[\exists n \in Nat : n^2 = 2] 表示存在一个自然数，该自然数的平方为2。该公式为假。

公式 latexmath:[F] 对于集合 latexmath:[S] 中某个元素 latexmath:[x] 为真，等价于 latexmath:[F] 不是对 latexmath:[S] 中所有的元素 latexmath:[x] 为假。换句话说，以下表述不成立：latexmath:[\neg F] 对于 latexmath:[S] 中所有元素为真。因此，公式

[.text-center]
(1.1) latexmath:[(\exists x \in S : F) \equiv \neg (\forall x \in S : \neg F)]

为谓词逻辑的一个恒真命题，也就是收该公式对于标识符 latexmath:[S] 和 latexmath:[F] 所有可能取值都为真。

空集 latexmath:[\{\}] 不含任何元素，因此公式 latexmath:[\exists x \in \{\}:F] 对于任何 latexmath:[F] 都为假。根据（1.1）可得公式 latexmath:[\forall x \in \{\}:F] 对于任何 latexmath:[F] 都为真。

公式 latexmath:[\forall x \in S>F] 和 latexmath:[\exists x \in S>F] 中的量化（quantification）被称作是有界的（bounded）。其原因是这些公式所做出的断言的主体是一个集合中的元素。无界的量化（unbounded quantification）也是有的。公式 latexmath:[\forall x > F] 就是在说 latexmath:[F] 对于 latexmath:[x] 所有的值都为真，而公式 latexmath:[\exists x > F] 是说至少有一个 latexmath:[x] 的值使得 latexmath:[F] 为真，但这里并没表明该值属于任何一个特定的集合。有界和无界可以被以下的恒真命题联系起来：

[.text-center]
latexmath:[(\forall x \in S:F) \equiv (\forall x:(x\in S) \implies F)]
[.text-center]
latexmath:[(\exists x \in S:F) \equiv (\exists x:(x\in S) \wedge F)]


恒真式（1.1）对于无界量词来说同样还是恒真式：

[.text-center]
latexmath:[(\exists x :F) \equiv \neg(\forall x: \neg F)]

在写规范的时候，应该尽量去使用有界量化，从而让规范更容易被人和计算机所理解。

全称量化概括了逻辑与操作。如果 latexmath:[S] 是一个有限集合，则 latexmath:[\forall x \in S:F] 是将 latexmath:[F] 中的 latexmath:[x] 替换为 latexmath:[X] 中不同元素后得到所有公式的逻辑与连接。例如，

[.text-center]
latexmath:[(\forall x \in \{2,3,7\} : x < y^x ) \equiv (2< y^2) \wedge (3<y^3) \wedge (7<y^7)]

有时候当我们提到无限多的公式的逻辑与时，从形式化角度的意思是一个全称量词修饰的公式。例如，对于所有自然数 latexmath:[x] 的公式 latexmath:[x \leq y^x] 的逻辑与就写成 latexmath:[\forall x \in Nat:x \leq y^x]。类似地，存在量化概括了逻辑或操作。

逻辑学家使用很多规则用于证明类似（1.1）的恒真命题，但是读者并不需要这些去学习或使用这些规则。读者们对谓词逻辑熟悉只需要达到能够一眼看懂那些简单恒真式的程度。把 latexmath:[\forall] 想成逻辑与以及把 latexmath:[\exists] 想成逻辑或应该能帮助读者熟悉谓词逻辑。例如，从或和与操作的结合律和交换律可得出以下恒真式：

[.text-center]
latexmath:[(\forall x \in S : F) \wedge (\forall x \in S:G) \equiv (\forall x \in S: F \wedge G)]
[.text-center]
latexmath:[(\exists x \in S : F) \vee (\exists x \in S:G) \equiv (\exists x \in S: F \vee G)]

对于任意集合 latexmath:[S]，任意公式 latexmath:[F] 和 latexmath:[G].

数学家们会用一些缩写来表示嵌套的量词。例如：

latexmath:[\forall x \in S, y\in T:F]  意味着  latexmath:[\forall x \in S : (\forall y\in T:F)]

latexmath:[\exists w,x,y,z \in S:F]  意味着  latexmath:[\exists w \in S: (\exists x \in S : (\exists y\in S: (\exists z \in S: F)))]

对于表达式 latexmath:[\exists x \in S:F]，逻辑学家会说 latexmath:[x] 是一个约束变量或受限变量（bound variable），latexmath:[x] 在 latexmath:[F] 中每一次出现都是被约束的（bound）。例如，latexmath:[n] 是一个在公式 latexmath:[\exists n \in Nat:n+1 > n] 中的受限变量。非受限变量就是所谓的自由变量（free variable），而自由变量在公式中每一此出现都是所谓自由出现（free occurrences）。这种说法有点容易误导读者：因为替换该变量后该公式并没有被改变，一个受限变量其实并不是真正的出现在一个公式里。具体来说，以下两个公式是等价的。

latexmath:[\forall n \in Nat, n +1 > n] 和 latexmath:[\forall x \in Nat, x +1 > x]



=== 公式和语言


